name: CI

on:
  push:
    branches:
      - version-3

  pull_request:
    branches:
      - version-3

permissions:
  contents: read

jobs:
  rbs-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [3.4]

    steps:
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - uses: actions/checkout@v4

      - name: Install gems
        run: |
          bundle config set --local with 'build rbs'
          bundle install

      - name: Install rbs collection
        run: rbs collection install

      - name: Build SDK
        run: bundle exec rake build

      - name: RBS Test
        run: bundle exec rake rbs:test

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Supported ruby versions
        # Jruby 10 is expected to fail until fix is live: https://github.com/jruby/jruby/issues/8847
        ruby: [2.7, '3.0', 3.1, 3.2, 3.3, 3.4, jruby-9.4, jruby-10.0]
        env: [KITCHEN_SINK, CRT]

    steps:
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - uses: actions/checkout@v4

      - name: Setup ENV
        run: |
          echo "${{ matrix.env }}=1" >> $GITHUB_ENV

      - name: Install gems
        run: |
          bundle config set --local with 'build test'
          bundle install

      - name: Build SDK
        run: bundle exec rake build

      - name: Test
        env:
          JRUBY_OPTS: -J-Xmx4g
        run: bundle exec rake test:spec
